# Exercício:

## 01 – Dados as operações abaixo, em Python, qual o resultado da operação lógica: 
p and q and r and s and t?
<br>
<br>Imprima os objetos e o resultado usando uma estrutura condicional.

<br>p = 2.0 + 3.0 / 5.0 == 10
<br>q = (p + 10.2) - 5.0 * 2.0 <= 2.9
<br>r = 10 <= p / q + 33.8 < 100
<br>s = 5 != p / (q + r)
<br>t = 33 == s * 2

In [1]:
p = 2.0 + 3.0 / 5.0 == 10
q = (p + 10.2) - 5.0 * 2.0 <= 2.9
r = 10 <= p / q + 33.8 < 100
s = 5 != p / (q + r)
t = 33 == s * 2

print(f"p: {p} \n q: {q} \n r: {r} \n s: {s} \n t: {t} \n")
print(p and q and r and s and t)

p: False
 q: True
 r: True
 s: True
 t: False

False

In [2]:
if p:
    print(f"p is {p}")
else:
    print(f"p is {p}")

p is False

In [3]:
if q:
    print(f"q is {q}")
else:
    print(f"q is {q}")

q is True

In [4]:
if r:
    print(f"r is {r}")
else:
    print(f"r is {r}")

r is True

In [5]:
if s:
    print(f"s is {s}")
else:
    print(f"s is {s}")

s is True

In [6]:
if t:
    print(f"t is {t}")
else:
    print(f"t is {t}")

t is False

In [7]:
if p and q and r and s and t:
    print("All variables are true")
else:
    print("At least one variable is false")

At least one variable is false

## Instancie um objeto da classe array numpy, contendo 5 valores quantitativos randômicos normalmente distribuídos, com média 10 e desvio padrão 3. 
Quantos e quais são os valores superiores a 10?

## 02 – Descreva o racional da sua resposta:

R.: Primeiro precisamos instanciar este objeto contendo os valores segundo os requisitos do exercício. Usando uma estrutura condicional para cada valor no array, verificamos se o valor é superior à 10, em caso positivo, imprimimos o valor e incrementamos o contador. Em caso negativo não fazemos nada. Ao final o número de valores superiores a 10 é impresso.

## 03 – Desenhe o fluxograma da resposta:

<img src="./img/10-fluxograma_exercício3_2.png" width="1200" />

## 04 – Escreva o programa em Python:

In [8]:
import numpy as np

In [9]:
# Instânciando o objeto array do numpy
array_randomico = np.random.normal(loc=10, scale=3, size=5)
array_randomico

array([ 7.88270074,  9.98356477,  9.27278602,  8.87075593, 10.51573289])

In [10]:
# Número de valores são superiores a 10
superior_a_10 = 0
alvo = 10
if array_randomico[0] > alvo:
    print(f"O valor {array_randomico[0]} é superior a {alvo}")
    superior_a_10 += 1
if array_randomico[1] > alvo:
    print(f"O valor {array_randomico[1]} é superior a {alvo}")
    superior_a_10 += 1
if array_randomico[2] > alvo:
    print(f"O valor {array_randomico[2]} é superior a {alvo}")
    superior_a_10 += 1
if array_randomico[3] > alvo:
    print(f"O valor {array_randomico[3]} é superior a {alvo}")
    superior_a_10 += 1
if array_randomico[4] > alvo:
    print(f"O valor {array_randomico[4]} é superior a {alvo}")
    superior_a_10 += 1
print(f"O número de valores superiores a {alvo} é: {superior_a_10}")

O valor 10.51573288698968 é superior a 10
O número de valores superiores a 10 é: 1

## 05 – Seria possível, com o racional proposto, saber quantos e quais valores são superiores a 20? Porque?

In [11]:
# Número de valores são superiores a 10
superior_a_10 = 0
alvo = 20
if array_randomico[0] > alvo:
    print(f"O valor {array_randomico[0]} é superior a {alvo}")
    superior_a_10 += 1
if array_randomico[1] > alvo:
    print(f"O valor {array_randomico[1]} é superior a {alvo}")
    superior_a_10 += 1
if array_randomico[2] > alvo:
    print(f"O valor {array_randomico[2]} é superior a {alvo}")
    superior_a_10 += 1
if array_randomico[3] > alvo:
    print(f"O valor {array_randomico[3]} é superior a {alvo}")
    superior_a_10 += 1
if array_randomico[4] > alvo:
    print(f"O valor {array_randomico[4]} é superior a {alvo}")
    superior_a_10 += 1
print(f"O número de valores superiores a {alvo} é: {superior_a_10}")

O número de valores superiores a 20 é: 0

## 06 – Instancie um objeto da classe lista com os valores obtidos no exercício 02.

O valor 10.453444246931676 está presente?

In [12]:
alvo = 10.453444246931676

if np.any(array_randomico == {alvo}):
    print(f"O valor {alvo} está presente no array.")
else:
    print(f"O valor {alvo} não está presente no array.")

O valor 10.453444246931676 não está presente no array.

## No exercício 7 da aula 6, foi instanciado um objeto da classe DataFrame. Exporte (usando nome_data_frame.to_csv(‘nome_arquivo.csv’)) para .csv estes dados e os importe (com pd.read_csv(‘nome_arquivo.csv’) aqui. Edite o objeto para que os index sejam os nomes dos genes e para que as colunas sejam facilmente identificadas. Usando o número de caracteres do primeiro gene, quero saber a informação gênica. Caso o nome tenha entre 2 e 4 caracteres inclusive, posso saber as informações do gene? Porém, caso tenha menos de 2 caracteres, posso saber todos os valores nas instâncias onde os números de caracteres dos nomes são superiores a 4? Ainda, caso tenha mais de 4 caracteres, apenas me informe quem é superior.

## 07 – Descreva o racional da sua resposta:

R.: Importar e configurar o objeto DataFrame. Instanciar variáveis que receberam os valores máximo (4), mínimo (2), n caracteres e colunas que podem ser usadas como resposta. Verificar inicialmente com operadores relacionais e lógicos o intervalo. Caso este não seja atendido analisar caso tenha menos de 2. Caso este não seja atendido, indicar isso ao usuário

## 08 – Desenhe o fluxograma da resposta:

<img src="./img/10-fluxograma_exercício7.png" width="1200" />

## 09 – Escreva o programa em Python:

In [13]:
import pandas as pd

In [14]:
df = pd.read_csv("./data/df_genes_aula6exer7.csv", index_col="Unnamed: 0")
df

         num_letras primeiras_duas_letras  num_a  contains_hu
isg15             5                    is      0        False
hur               3                    hu      0         True
ifna              4                    if      1        False
tnfa              4                    tn      1        False
atpsf1a           7                    at      2        False

In [15]:
num_gene = 0
maximo = 4
minimo = 2

gene_teste = df.iloc[num_gene, :]
gene_teste

num_letras                   5
primeiras_duas_letras       is
num_a                        0
contains_hu              False
Name: isg15, dtype: object

In [16]:
# Caso o nome tenha entre 2 e 4 caracteres inclusive, 
if minimo < gene_teste['num_letras'] <= maximo:
    # posso saber as informações do gene?
    print("Informações do gene:")
    print(gene_teste)

# Porém, caso tenha menos de 2 caracteres, 
elif gene_teste['num_letras'] < minimo:
    # posso saber todos os valores nas instâncias onde os 
    # números de caracteres dos nomes são superiores a 4?
    print("Valores nas instâncias:")
    display(df[df['num_letras'] > 4])

else:
    # Ainda, caso tenha mais de 4 caracteres, apenas me informe quem é superior.
    print("Quem é superior:")
    display(df[df['num_letras'] > 4].index)

Quem é superior:

Index(['isg15', 'atpsf1a'], dtype='object')

In [17]:
# Caso o nome tenha entre 2 e 4 caracteres inclusive, 
num_gene = 2
maximo = 4
minimo = 2

gene_teste = df.iloc[num_gene, :]
gene_teste

num_letras                   4
primeiras_duas_letras       if
num_a                        1
contains_hu              False
Name: ifna, dtype: object

In [18]:
# Caso o nome tenha entre 2 e 4 caracteres inclusive, 
if minimo < gene_teste['num_letras'] <= maximo:
    # posso saber as informações do gene?
    print("Informações do gene:")
    print(gene_teste)

# Porém, caso tenha menos de 2 caracteres, 
elif gene_teste['num_letras'] < minimo:
    # posso saber todos os valores nas instâncias onde os 
    # números de caracteres dos nomes são superiores a 4?
    print("Valores nas instâncias:")
    display(df[df['num_letras'] > 4])

else:
    # Ainda, caso tenha mais de 4 caracteres, apenas me informe quem é superior.
    print("Quem é superior:")
    display(df[df['num_letras'] > 4].index)

Informações do gene:
num_letras                   4
primeiras_duas_letras       if
num_a                        1
contains_hu              False
Name: ifna, dtype: object

In [19]:
# Porém, caso tenha menos de 2 caracteres, 
num_gene = 1
maximo = 5
minimo = 4

gene_teste = df.iloc[num_gene, :]
gene_teste

num_letras                  3
primeiras_duas_letras      hu
num_a                       0
contains_hu              True
Name: hur, dtype: object

In [20]:
# Caso o nome tenha entre 2 e 4 caracteres inclusive, 
if minimo < gene_teste['num_letras'] <= maximo:
    # posso saber as informações do gene?
    print("Informações do gene:")
    print(gene_teste)

# Porém, caso tenha menos de 2 caracteres, 
elif gene_teste['num_letras'] < minimo:
    # posso saber todos os valores nas instâncias onde os 
    # números de caracteres dos nomes são superiores a 4?
    print("Valores nas instâncias:")
    display(df[df['num_letras'] > 4])

else:
    # Ainda, caso tenha mais de 4 caracteres, apenas me informe quem é superior.
    print("Quem é superior:")
    display(df[df['num_letras'] > 4].index)

Valores nas instâncias:

         num_letras primeiras_duas_letras  num_a  contains_hu
isg15             5                    is      0        False
atpsf1a           7                    at      2        False

## 10 – Caso a DataFrame contenha 10 milhões de entradas, este racional utilizado poderia responder as mesmas perguntas? Porque?

R.: Sim, porque o código verifica cada uma das instâncias individualmente, não importando o número de instâncias na DataFrame. Porém, outras estruturas podem ser necessárias para uma análise de um conjunto sde dados com esse número de entradas.